### ISSUE TITLE
No Description on how to use in projects like react.

### ISSUE THREAD

**Issue by nakullondhe** [Drarig29/brackets-viewer.js#20]
It would be really helpful if we have details about using on react  or other libraries

**Comment by Drarig29** [comment]
I just created an example for you: https://repl.it/@Drarig29/brackets-viewerjs-React

Basically, there is no React component created in this library because all the rendering is done manually with a defined CSS file and a JS file which adds `bracketsViewer.render()` in the `window` object.

So, just add this in your `index.html` file as stated in the README:

```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Drarig29/brackets-viewer.js/dist/brackets-viewer.min.css" />
<script type="text/javascript" src="https://cdn.jsdelivr.net/gh/Drarig29/brackets-viewer.js/dist/brackets-viewer.min.js"></script>
```

Or you could install the package using npm or yarn and serve these files from your `node_modules` folder (please don't serve the whole folder 😅).

Once you've done that, you can make your React component to wrap the viewer. For example:

```js
import React from 'react';

const DB_URL = 'https://raw.githubusercontent.com/Drarig29/brackets-viewer.js/master/demo/db.json';

class Viewer extends React.Component {
  async componentDidMount() {
    const db = await fetch(DB_URL).then(r => r.json());
    
    window.bracketsViewer.render('#root', {
      stage: db.stage[0],
      groups: db.group,
      rounds: db.round,
      matches: db.match,
      matchGames: db.match_game,
      participants: db.participant,
    }, {
      participantOriginPlacement: 'before',
      showSlotsOrigin: true,
      showLowerBracketSlotsOrigin: true,
      highlightParticipantOnHover: true,
    });
  }
  
  render() {
    return <div id="root"></div>;
  }
}

export default Viewer;
```

I just took the same code as in the [`/demo`](https://github.com/Drarig29/brackets-viewer.js/tree/master/demo) folder.

Obviously, you would host your own database and fetch this one (not my static demo `db.json` file). And this database would be manipulated by [brackets-manager.js](https://github.com/Drarig29/brackets-manager.js).

**Comment by Drarig29** [comment]
@nakullondhe closing this as you don't answer.

**Comment by sherman721** [comment]
I'm having an issue running this with React and displaying multiple brackets on one page. Here is my code:
`import React, { useEffect } from 'react';

async function render(data) {
    window.bracketsViewer.render('#root', {
        stages: data.stage,
        matches: data.match,
        matchGames: data.match_game,
        participants: data.participant,
    });
}

function Tournament({data}) {
    useEffect(() => {
        render(data)
    }, [data]);
    
    return <div id="root"></div>;
}`

I keep getting back the error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'forEach')  at e.BracketsViewer.render (brackets-viewer.min.js:1:13197)

Do you know how I can display multiple brackets?
